language: node_js
node_js:
- '4.0'
- '4.1'
- '5.1'
sudo: false
services:
before_install:
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
notifications:
  email: true
after_failure: cat npm-debug.log
branches:
  only:
  - master
env:
  global:
